apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-12-29T17:08:18Z"
  labels:
    kubernetes.io/metadata.name: mealie
  name: mealie
  resourceVersion: "56080"
  uid: 9cd89659-2251-4c5a-85c4-263f679cc3e9
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
